version: '3.8'

services:
  cui-tools:
    container_name: cui-tools-cpu
    build:
      context: .
      dockerfile: Dockerfile.cpu
    volumes:
      - .:/workspace
    working_dir: /workspace
    restart: unless-stopped
    env_file:
      - .env
